version: '3.8'

services:
  app:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    command: mvn spring-boot:run -Dspring-boot.run.fork=false
    volumes:
      - ./src:/app/src
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pismo_transactions
      - SPRING_DATASOURCE_USERNAME=pismo
      - SPRING_DATASOURCE_PASSWORD=pismo123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pismo-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pismo_transactions
      - POSTGRES_USER=pismo
      - POSTGRES_PASSWORD=pismo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pismo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pismo-network

volumes:
  postgres_data:

networks:
  pismo-network:
    driver: bridge